project:
  type: website
  output-dir: ../docs

website:
  title: "NUTRIVENTION Clinical Trial" #UPDATE ME
  navbar:
    left:
      - icon: github
        href: "https://github.com/mskcc-microbiome/2025_shah_nutrivention_pilot" # UPDATE ME
  sidebar:
    style: "floating"
    search: true
    collapse-level: 3
    contents: 
      - section: "Project Information"
        contents: 
          - text: "View Notes"
            href: 00-notes_browsing.qmd
          - text: "Introduction"
            href: 01-project_notes_and_intro.qmd
      - section: "Analyses"
        contents: 
          - text: "Overview of all Analyses"
            href: index.qmd
          - text: "RNA Seq Analysis"
            href: analyses/rna_seq.qmd
          - text: "Cazyme Analysis"
            href: analyses/cazyme.qmd
          - text: "Body Composition\nAnalysis"
            href: analyses/body_comp.qmd

format:
  html:
    theme: 
      - minty 
      - custom.scss 
